#pragma once

#include <string_view>

enum class SocketHeader {
	ALIEN_AND_COLOR,
	CARDS_AND_TURN_ORDER,
	ALREADY_ARRIVED_PLAYERS,
	NEWLY_JOINED_PLAYER,
	STARTING_GAME,
	DRAWN_COLOR,
	CHOSEN_COLONY,
	COLONY_INFORMATION,
	DESTINY_DRAW_INFO,
	DESTINY_DRAW_CHOICE,
};
